"""
AGENT 3: Data Cleaning Execution Agent
Applies the cleaning plan generated by the strategy agent.
Maintains before/after snapshots and logs all transformations.
"""
import pandas as pd
import numpy as np
from typing import Dict, Any, Tuple
from datetime import datetime
from agents.base_agent import BaseAgent
from utils.data_helpers import (
    CategoricalEncoder, DataScaler, MemoryOptimizer, 
    FeatureEngineer, CleaningLogger, DataQualityScorer
)

class CleaningExecutionAgent(BaseAgent):
    """
    Executes the cleaning plan using Pandas.
    Maintains audit trail of all transformations.
    """
    
    def __init__(self):
        super().__init__("CleaningExecutionAgent")
        self.original_df = None
        self.cleaned_df = None
        self.transformation_log = []
        self.snapshots = {}
        self.cleaning_logger = CleaningLogger()
    
    def execute(self, df: pd.DataFrame, plan: Dict[str, Any]) -> Dict[str, Any]:
        """
        Main execution method (optimized - minimal copying for large data)
        
        Args:
            df: Original DataFrame
            plan: Cleaning plan from strategy agent
            
        Returns:
            Cleaned DataFrame and transformation log
        """
        self._mark_status("running")
        start_time = datetime.now()
        
        try:
            # Only copy small datasets, for large ones use reference (memory optimization)
            self.original_df = df.copy() if len(df) < 100000 else df
            self.cleaned_df = df.copy()
            
            self.logger.logger.info(f"Starting cleaning execution. Original shape: {df.shape}")
            if len(df) < 100000:
                self.snapshots['original'] = self.original_df.copy()
            
            # Step 1: Apply row-level actions
            self._execute_row_actions(plan['row_actions'])
            
            # Step 2: Apply column-level actions
            self._execute_column_actions(plan['actions'])
            
            # Step 3: Apply categorical encoding
            if 'encoding_actions' in plan:
                self._execute_encoding_actions(plan['encoding_actions'])
            
            # Step 4: Apply scaling/normalization
            if 'scaling_actions' in plan:
                self._execute_scaling_actions(plan['scaling_actions'])
            
            # Step 5: Memory optimization for large datasets
            if 'memory_optimization' in plan and plan['memory_optimization'].get('recommend_optimization'):
                self._optimize_memory()
            
            # Step 6: Apply auto feature engineering
            if 'feature_engineering' in plan and plan['feature_engineering'].get('recommended'):
                self._execute_feature_engineering(plan['feature_engineering'])
            
            # Step 7: Calculate final data quality
            quality_after = DataQualityScorer.calculate_overall_quality_score(self.cleaned_df)
            
            # Step 8: Final validation
            self._post_cleaning_validation()
            
            # Skip cleaned snapshot for very large data
            if len(self.cleaned_df) < 100000:
                self.snapshots['cleaned'] = self.cleaned_df.copy()
            self._mark_status("completed")
            
            duration = (datetime.now() - start_time).total_seconds()
            self.execution_time = duration
            
            self.logger.logger.info(f"Cleaning completed in {duration:.2f}s")
            self.logger.logger.info(f"Final shape: {self.cleaned_df.shape}")
            
            return {
                'status': 'success',
                'original_shape': df.shape,
                'cleaned_shape': self.cleaned_df.shape,
                'rows_removed': df.shape[0] - self.cleaned_df.shape[0],
                'columns_removed': df.shape[1] - self.cleaned_df.shape[1],
                'transformations': len(self.transformation_log),
                'execution_time': duration,
                'cleaned_df': self.cleaned_df,
                'log': self.transformation_log,
                'quality_score': quality_after,
                'human_readable_log': self.cleaning_logger.get_human_readable_log()
            }
            
        except Exception as e:
            self.logger.log_error(str(e))
            self._mark_status("failed")
            return {
                'status': 'error',
                'error': str(e),
                'execution_time': (datetime.now() - start_time).total_seconds()
            }
    
    def _execute_row_actions(self, row_actions: Dict[str, Any]):
        """Execute row-level cleaning actions (optimized for large datasets)"""
        for action in row_actions.get('actions', []):
            action_type = action['action']
            
            if action_type == 'DROP_DUPLICATES':
                rows_before = len(self.cleaned_df)
                # Use subset parameter for faster duplicate detection if columns specified
                subset = action.get('subset', None)
                self.cleaned_df = self.cleaned_df.drop_duplicates(subset=subset)
                rows_after = len(self.cleaned_df)
                rows_dropped = rows_before - rows_after
                
                log_entry = {
                    'step': len(self.transformation_log) + 1,
                    'action': action_type,
                    'rows_before': rows_before,
                    'rows_after': rows_after,
                    'rows_affected': rows_dropped,
                    'status': 'success'
                }
                self.transformation_log.append(log_entry)
                self.logger.logger.info(f"Dropped {rows_dropped} duplicate rows")
                self.logger.log_decision(
                    column='[ROWS]',
                    decision=action_type,
                    reasoning=f"Removed {rows_dropped} duplicates",
                    confidence=0.95
                )
            
            elif action_type == 'DROP_EMPTY_ROWS':
                rows_before = len(self.cleaned_df)
                self.cleaned_df = self.cleaned_df.dropna(how='all')
                rows_after = len(self.cleaned_df)
                rows_dropped = rows_before - rows_after
                
                log_entry = {
                    'step': len(self.transformation_log) + 1,
                    'action': action_type,
                    'rows_before': rows_before,
                    'rows_after': rows_after,
                    'rows_affected': rows_dropped,
                    'status': 'success'
                }
                self.transformation_log.append(log_entry)
                self.logger.logger.info(f"Dropped {rows_dropped} empty rows")
    
    def _execute_column_actions(self, column_actions: list):
        """Execute column-level cleaning actions"""
        
        for action in column_actions:
            col_name = action['column']
            action_type = action['action']
            
            try:
                if action_type == 'DROP':
                    if col_name in self.cleaned_df.columns:
                        self.cleaned_df = self.cleaned_df.drop(columns=[col_name])
                        log_entry = {
                            'step': len(self.transformation_log) + 1,
                            'action': action_type,
                            'column': col_name,
                            'reason': action.get('reason', 'unknown'),
                            'status': 'success'
                        }
                        self.transformation_log.append(log_entry)
                        self.logger.logger.info(f"Dropped column: {col_name}")
                
                elif action_type == 'IMPUTE':
                    method = action.get('method')
                    missing_before = self.cleaned_df[col_name].isnull().sum()
                    
                    if method == 'median':
                        median_val = self.cleaned_df[col_name].median()
                        self.cleaned_df[col_name] = self.cleaned_df[col_name].fillna(median_val)
                    
                    elif method == 'mean':
                        mean_val = self.cleaned_df[col_name].mean()
                        self.cleaned_df[col_name] = self.cleaned_df[col_name].fillna(mean_val)
                    
                    elif method == 'mode':
                        mode_val = self.cleaned_df[col_name].mode()
                        fill_val = mode_val[0] if len(mode_val) > 0 else 'UNKNOWN'
                        self.cleaned_df[col_name] = self.cleaned_df[col_name].fillna(fill_val)
                    
                    elif method == 'forward_fill':
                        # Use interpolate for better performance than deprecated fillna(method='ffill')
                        self.cleaned_df[col_name] = self.cleaned_df[col_name].interpolate(method='pad', limit_direction='both')
                        # Fill remaining NaNs with backward fill
                        self.cleaned_df[col_name] = self.cleaned_df[col_name].bfill()
                    
                    missing_after = self.cleaned_df[col_name].isnull().sum()
                    log_entry = {
                        'step': len(self.transformation_log) + 1,
                        'action': action_type,
                        'column': col_name,
                        'method': method,
                        'values_imputed': int(missing_before),
                        'missing_before': int(missing_before),
                        'missing_after': int(missing_after),
                        'status': 'success'
                    }
                    self.transformation_log.append(log_entry)
                    self.logger.logger.info(f"Imputed {missing_before} values in {col_name} using {method}")
                    self.logger.log_decision(
                        column=col_name,
                        decision=f"IMPUTE ({method})",
                        reasoning=f"Filled {missing_before} missing values",
                        confidence=0.90
                    )
                
                elif action_type == 'FORWARD_FILL':
                    missing_before = self.cleaned_df[col_name].isnull().sum()
                    # Use interpolate instead of deprecated pad method
                    self.cleaned_df[col_name] = self.cleaned_df[col_name].interpolate(method='pad', limit_direction='both')
                    self.cleaned_df[col_name] = self.cleaned_df[col_name].bfill()
                    missing_after = self.cleaned_df[col_name].isnull().sum()
                    
                    log_entry = {
                        'step': len(self.transformation_log) + 1,
                        'action': action_type,
                        'column': col_name,
                        'values_filled': int(missing_before),
                        'missing_before': int(missing_before),
                        'missing_after': int(missing_after),
                        'status': 'success'
                    }
                    self.transformation_log.append(log_entry)
                    self.logger.logger.info(f"Forward filled {missing_before} values in {col_name}")
                
                elif action_type == 'DROP_ROWS':
                    rows_before = len(self.cleaned_df)
                    colname = action.get('target', col_name)
                    self.cleaned_df = self.cleaned_df.dropna(subset=[colname])
                    rows_after = len(self.cleaned_df)
                    
                    log_entry = {
                        'step': len(self.transformation_log) + 1,
                        'action': action_type,
                        'column': colname,
                        'rows_before': rows_before,
                        'rows_after': rows_after,
                        'rows_dropped': rows_before - rows_after,
                        'status': 'success'
                    }
                    self.transformation_log.append(log_entry)
                    self.logger.logger.info(f"Dropped {rows_before - rows_after} rows with missing {colname}")
                
                elif action_type == 'KEEP':
                    # No action needed
                    log_entry = {
                        'step': len(self.transformation_log) + 1,
                        'action': action_type,
                        'column': col_name,
                        'status': 'skipped'
                    }
                    self.transformation_log.append(log_entry)
                    self.logger.logger.info(f"Kept column: {col_name} (no changes)")
            
            except Exception as e:
                error_msg = f"Error processing {col_name}: {str(e)}"
                self.logger.log_error(error_msg, col_name)
                log_entry = {
                    'step': len(self.transformation_log) + 1,
                    'action': action_type,
                    'column': col_name,
                    'status': 'failed',
                    'error': str(e)
                }
                self.transformation_log.append(log_entry)
    
    def _execute_encoding_actions(self, encoding_actions: Dict[str, Any]):
        """Execute categorical encoding actions"""
        
        if not encoding_actions.get('actions'):
            self.logger.logger.info("No encoding actions to execute")
            return
        
        encoder = CategoricalEncoder()
        
        for action in encoding_actions['actions']:
            col_name = action['column']
            encoding_method = action['method']
            
            try:
                if col_name not in self.cleaned_df.columns:
                    self.logger.logger.warning(f"Column {col_name} not found for encoding")
                    continue
                
                if encoding_method == 'one_hot':
                    self.cleaned_df = encoder.one_hot_encode(self.cleaned_df, col_name)
                    
                    log_entry = {
                        'step': len(self.transformation_log) + 1,
                        'action': 'ENCODE',
                        'column': col_name,
                        'method': 'one_hot',
                        'new_columns': encoder.encoded_columns.get(col_name, []),
                        'status': 'success'
                    }
                    self.transformation_log.append(log_entry)
                    self.logger.logger.info(f"One-hot encoded column: {col_name}")
                    self.logger.log_decision(
                        column=col_name,
                        decision='ENCODE (ONE-HOT)',
                        reasoning=action['reasoning'],
                        confidence=action['confidence_score']
                    )
                
                elif encoding_method == 'label':
                    self.cleaned_df = encoder.label_encode(self.cleaned_df, col_name)
                    
                    log_entry = {
                        'step': len(self.transformation_log) + 1,
                        'action': 'ENCODE',
                        'column': col_name,
                        'method': 'label',
                        'unique_values': int(action.get('unique_values', 0)),
                        'status': 'success'
                    }
                    self.transformation_log.append(log_entry)
                    self.logger.logger.info(f"Label encoded column: {col_name}")
                    self.logger.log_decision(
                        column=col_name,
                        decision='ENCODE (LABEL)',
                        reasoning=action['reasoning'],
                        confidence=action['confidence_score']
                    )
            
            except Exception as e:
                error_msg = f"Error encoding {col_name}: {str(e)}"
                self.logger.log_error(error_msg, col_name)
                log_entry = {
                    'step': len(self.transformation_log) + 1,
                    'action': 'ENCODE',
                    'column': col_name,
                    'method': encoding_method,
                    'status': 'failed',
                    'error': str(e)
                }
                self.transformation_log.append(log_entry)
    
    def _execute_scaling_actions(self, scaling_actions: Dict[str, Any]):
        """Execute scaling/normalization actions"""
        
        if not scaling_actions.get('actions'):
            self.logger.logger.info("No scaling actions to execute")
            return
        
        scale_method = scaling_actions.get('scale_method', 'standard')
        scaler = DataScaler(method=scale_method)
        
        # Get all columns to scale
        columns_to_scale = [action['column'] for action in scaling_actions['actions']]
        columns_to_scale = [col for col in columns_to_scale if col in self.cleaned_df.columns]
        
        if not columns_to_scale:
            self.logger.logger.info("No valid columns to scale")
            return
        
        try:
            self.cleaned_df = scaler.fit_and_scale(self.cleaned_df, columns_to_scale)
            
            log_entry = {
                'step': len(self.transformation_log) + 1,
                'action': 'SCALE',
                'method': scale_method,
                'columns_scaled': columns_to_scale,
                'count': len(columns_to_scale),
                'status': 'success'
            }
            self.transformation_log.append(log_entry)
            self.logger.logger.info(f"Scaled {len(columns_to_scale)} numeric columns using {scale_method} normalization")
            self.logger.log_decision(
                column='[NUMERIC]',
                decision=f'SCALE ({scale_method.upper()})',
                reasoning=f'Applied {scale_method} normalization to {len(columns_to_scale)} numeric columns',
                confidence=0.95
            )
        
        except Exception as e:
            error_msg = f"Error scaling columns: {str(e)}"
            self.logger.log_error(error_msg)
            log_entry = {
                'step': len(self.transformation_log) + 1,
                'action': 'SCALE',
                'method': scale_method,
                'status': 'failed',
                'error': str(e)
            }
            self.transformation_log.append(log_entry)
    
    def _optimize_memory(self):
        """Optimize memory usage by converting data types"""
        try:
            memory_before = MemoryOptimizer.estimate_memory(self.cleaned_df)
            
            self.cleaned_df, optimizations = MemoryOptimizer.optimize_dtypes(self.cleaned_df)
            
            memory_after = MemoryOptimizer.estimate_memory(self.cleaned_df)
            reduction = MemoryOptimizer.get_memory_reduction(
                memory_before['mb'], 
                memory_after['mb']
            )
            
            log_entry = {
                'step': len(self.transformation_log) + 1,
                'action': 'MEMORY_OPTIMIZATION',
                'optimizations_applied': len(optimizations),
                'memory_before_mb': memory_before['mb'],
                'memory_after_mb': memory_after['mb'],
                'reduction_mb': reduction['reduction_mb'],
                'reduction_percent': reduction['reduction_percent'],
                'status': 'success'
            }
            self.transformation_log.append(log_entry)
            self.logger.logger.info(
                f"Memory optimized: {memory_before['mb']:.2f}MB → {memory_after['mb']:.2f}MB "
                f"({reduction['reduction_percent']:.1f}% reduction)"
            )
            
            self.cleaning_logger.add_entry(
                stage='EXECUTION',
                action='MEMORY_OPTIMIZATION',
                details={
                    'memory_before_mb': memory_before['mb'],
                    'memory_after_mb': memory_after['mb'],
                    'reduction_percent': reduction['reduction_percent'],
                    'optimizations': optimizations
                },
                reasoning='Applied dtype optimization to reduce memory footprint',
                confidence=0.95
            )
            
        except Exception as e:
            error_msg = f"Error optimizing memory: {str(e)}"
            self.logger.log_error(error_msg)
            log_entry = {
                'step': len(self.transformation_log) + 1,
                'action': 'MEMORY_OPTIMIZATION',
                'status': 'failed',
                'error': str(e)
            }
            self.transformation_log.append(log_entry)
    
    def _execute_feature_engineering(self, fe_plan: Dict[str, Any]):
        """Execute auto feature engineering"""
        try:
            features_before = self.cleaned_df.shape[1]
            
            self.cleaned_df, features_created = FeatureEngineer.generate_features(self.cleaned_df)
            
            features_after = self.cleaned_df.shape[1]
            features_added = features_after - features_before
            
            log_entry = {
                'step': len(self.transformation_log) + 1,
                'action': 'FEATURE_ENGINEERING',
                'features_before': features_before,
                'features_after': features_after,
                'features_added': features_added,
                'new_features': list(features_created.keys()),
                'status': 'success'
            }
            self.transformation_log.append(log_entry)
            
            self.logger.logger.info(
                f"Auto feature engineering: {features_before} → {features_after} features (+{features_added})"
            )
            
            self.cleaning_logger.add_entry(
                stage='EXECUTION',
                action='FEATURE_ENGINEERING',
                details={
                    'features_created': features_created,
                    'count': features_added
                },
                reasoning='Applied automatic feature engineering to generate new predictive features',
                confidence=0.80
            )
            
        except Exception as e:
            error_msg = f"Error in feature engineering: {str(e)}"
            self.logger.log_error(error_msg)
            log_entry = {
                'step': len(self.transformation_log) + 1,
                'action': 'FEATURE_ENGINEERING',
                'status': 'failed',
                'error': str(e)
            }
            self.transformation_log.append(log_entry)
    
    def _post_cleaning_validation(self):
        """Validate the cleaned data"""
        self.logger.logger.info("Running post-cleaning validation...")
        
        # Check data types consistency
        # Check for any remaining completely empty columns
        empty_cols = [col for col in self.cleaned_df.columns if self.cleaned_df[col].isnull().all()]
        if empty_cols:
            self.logger.logger.warning(f"Found empty columns after cleaning: {empty_cols}")
            self.cleaning_logger.add_entry(
                stage='VALIDATION',
                action='WARNING_EMPTY_COLUMNS',
                details={'columns': empty_cols},
                reasoning='Found completely empty columns after cleaning',
                confidence=0.99
            )
        
        # Log final statistics
        self.cleaning_logger.add_entry(
            stage='VALIDATION',
            action='FINAL_STATISTICS',
            details={
                'rows': self.cleaned_df.shape[0],
                'columns': self.cleaned_df.shape[1],
                'memory_mb': MemoryOptimizer.estimate_memory(self.cleaned_df)['mb']
            },
            reasoning='Final dataset shape and properties after all transformations',
            confidence=1.0
        )
        
        self.logger.logger.info("Post-cleaning validation completed")
    
    def get_cleaning_logger(self) -> CleaningLogger:
        """Return the cleaning logger for detailed transformation logs"""
        return self.cleaning_logger
    
    def get_cleaned_df(self) -> pd.DataFrame:
        """Return the cleaned DataFrame"""
        return self.cleaned_df
    
    def get_original_df(self) -> pd.DataFrame:
        """Return the original DataFrame"""
        return self.original_df
    
    def get_transformation_log(self) -> list:
        """Return the transformation log"""
        return self.transformation_log
